export const SVGS = {
    logo : require('./logo.svg').default,
    phone : require('./phone.svg').default,
    chevron_down : require('./chevron-down.svg').default,
    farme : require('./farme.svg').default,
    tabbar : require('./tabbar.svg').default,
    close: require('./close.svg').default,
    discovery: require('./discovery.svg').default,
    zalo: require('./zalo.svg').default,
    messenger: require('./messenger.svg').default,
    call: require('./call.svg').default,
    star: require('./star.svg').default,
    map: require('./map-pin.svg').default,
    blu_bg: require('./blu-bg.svg').default,
    one: require('./1.svg').default,
    two: require('./2.svg').default,
    zalo_nav: require('./zalo-nav.svg').default,
    about_us: require('./about-us.svg').default,
    user: require('./user.svg').default,
    mul_star: require('./mul-star.svg').default,
    heart: require('./heart.svg').default,
    arrow_left: require('./arrow-left.svg').default,
    arrow_right: require('./arrow-right.svg').default,
    farme_no_active: require('./farme-no-active.svg').default,
    folow_1: require('./flow-1.svg').default,
    folow_2: require('./flow-2.svg').default,
    folow_2_2: require('./check.svg').default,
    folow_2_mobile: require('./flow-2-mobile.svg').default,
    viet_nam: require('./Vietnam.svg').default,
    abosolute_image: require('./abosolute-image.svg').default,
    
}